import * as main from "main";

// TODO: Implement a proper loading scheme

function load_assets( source_json ){
  let models = {};
  let images = {};

  return {models: models, images: images}
}
// TODO: Assets.json could easily be generated by a script

$(() => {
  let systems, spobs, models, images;
  let game_canvas = $('#gameCanvas');
  let engine = new BABYLON.Engine( game_canvas[0], true);
  let scene = new BABYLON.Scene(engine);
  
  // TODO: Set up a nice little loading screen in a canvas

  $.when(
    $.getJSON('data/systems.json', ( data ) =>  {
      systems = data;
      console.log(data);
    }),
    $.getJSON('data/spobs.json', ( data ) => {
      spobs = data;
      console.log(data);
    }),
    $.getJSON('data/assets.json', (data) => {
      let assets = load_assets(data);
      models = assets.models;
      images = assets.images;
    })
  ).then( () => {
    if (systems && spobs && models && images) {
      main.init(
        game_canvas, scene, engine,
        systems, spobs, models, images
      );
    }
  });
});

